#ifndef PREPROCESSORS
#define PREPROCESSORS

/*RESPONSE CODES & RX()/TX() RETURN VALUES*/
#define EMPTY 0x02  /*Not a return value, but a value to put in the rxReturn value to clear it after reading*/
#define ACK 0x00 /*ACKNOWLEDGE  PREVIOUSLY WAS 1*/
#define NAK 0xFF /*NEGATIVE ACKNOWLEDGE  PREVIOUSLY WAS 2*/
#define RET 0xAA /*RETRANSMIT   PREVIOUSLY WAS 3*/
#define NO_RESPONSE 0x4 /*NO RESPONSE RECEIVED*/
#define IGNORED 0x5 /*RECEIVED DATA SHOULD BE IGNORED*/
#define RECEIVED 0x6 /*RECEIVED DATA SHOULD BE LOOKED AT*/
#define DISORDERED 0x7 /*RECEIVED DATA IS NOT WHAT IS EXPECTED*/
#define DISTORTED 0x8 /*RECIEVED DATA IS DISTORTED*/
/*DEVICE ADDRESSES*/
#define VMC_ADDRESS 0x00
#define CHANGER_ADDRESS 0x08
#define CASHLESS1_ADDRESS 0x10
#define COMMUNICATIONS_GATEWAY_ADDRESS 0x18
#define DISPLAY_ADDRESS 0x20
#define ENERGY_MANAGEMENT_SYSTEM_ADDRESS 0x28
#define BILL_VALIDATOR_ADDRESS 0x30
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL_ADDRESS 0x38
#define UNIVERSAL_SATELLITE_DEVICE1_ADDRESS 0x40
#define UNIVERSAL_SATELLITE_DEVICE2_ADDRESS 0x48
#define UNIVERSAL_SATELLITE_DEVICE3_ADDRESS 0x50
#define COIN_HOPPER1_ADDRESS 0x58
#define CASHLESS2_ADDRESS 0x60
#define AGE_VERIFICATION_DEVICE_ADDRESS 0x68
#define COIN_HOPPER2_ADDRESS 0x70
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL2_ADDRESS 0x78
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL3_ADDRESS 0x80
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL4_ADDRESS 0x88
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL5_ADDRESS 0x90
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL6_ADDRESS 0x98
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL7_ADDRESS 0xA0
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL8_ADDRESS 0xA8
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL9_ADDRESS 0xB0
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL10_ADDRESS 0xB8
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL11_ADDRESS 0xC0
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL12_ADDRESS 0xC8
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL13_ADDRESS 0xD0
#define RESERVED_FOR_FUTURE_STANDARD_PERIPHERAL14_ADDRESS 0xD8
#define EXPERIMENTAL_PERIPHERAL1_ADDRESS 0xE0
#define EXPERIMENTAL_PERIPHERAL2_ADDRESS 0xE8
#define VENDING_MACHINE_SPECIFIC_PERIPHERAL1_ADDRESS 0xF0
#define VENDING_MACHINE_SPECIFIC_PERIPHERAL2_ADDRESS 0xF8

/*CHRONOLOGIC() COMMANDS (INCOMING)*/
#define TIMER_RESET 0
#define TIMER_UPDATE 1

/*CHRONOLOGIC() ZRETURN VALUES (OUTGOING)*/
#define OK 0x0
#define T_INTER_BYTE 0x1 /*RECIEVED TRANSMISSION COMPLETED & INTER-BYTE TIME-OUT HAS BEEN REACHED BEFORE A RESPONSE*/
#define T_RESPONSE 0x2   /*TRANSMISSION COMPLETED & NON-RESPONSE TIME REACHED BEFORE A RESPONSE*/
#define T_BREAK 0x3      /*BUS RESET IS TAKING PLACE*/
#define T_SETUP 0x04     /*BUS RESET IS OVER*/

/*CASHLESS PAYMENT DEVICE*/
 #define CASHLESS_STATE_INACTIVE 0x1
 #define CASHLESS_STATE_DISABLED 0x2
 #define CASHLESS_STATE_ENABLED 0x03
 #define CASHLESS_STATE_SESSIONIDLE 0x04
 #define CASHLESS_STATE_VEND 0x05
 #define CASHLESS_STATE_ALWAYSIDLE 0x06
 #define CASHLESS_STATE_REVALUE 0x07
 #define CASHLESS_STATE_NEGATIVEVEND 0x08
 #define CASHLESS_RESET_COMMAND 0x0
 #define CASHLESS_SETUP_COMMAND 0x1
   #define CASHLESS_SETUP_CONFIGDATA_COMMAND 0x00
   #define CASHLESS_SETUP_CONFIGDATA_RESPONSE_READERCONFIGDATA 0x01
 #define CASHLESS_SETUP_MAXMINPRICES_COMMAND 0x01
 #define CASHLESS_POLL_COMMAND 0x2
   #define CASHLESS_POLL_RESPONSE_ 0x00
   #define CASHLESS_POLL_RESPONSE_READERCONFIGINFO 0x01
   #define CASHLESS_POLL_RESPONSE_DISPLAYREQUEST 0x02
   #define CASHLESS_POLL_RESPONSE_BEGINSESSION 0x03
   #define CASHLESS_POLL_RESPONSE_SESSIONCANCELREQUEST 0x04
   #define CASHLESS_POLL_RESPONSE_VENDAPPROVED 0x05
   #define CASHLESS_POLL_RESPONSE_VENDDENIED 0x06
   #define CASHLESS_POLL_RESPONSE_ENDSESSION 0x07
   #define CASHLESS_POLL_RESPONSE_CANCELLED 0x08
   #define CASHLESS_POLL_RESPONSE_PERIPHERALID 0x09
   #define CASHLESS_POLL_RESPONSE_MALFUNCTIONERROR 0x0A
   #define CASHLESS_POLL_RESPONSE_COMMANDOUTOFSEQUENCE 0x0B
   #define CASHLESS_POLL_RESPONSE_DIAGNOSTICRESPONSE 0xFF
   #define CASHLESS_POLL_RESPONSE_REVALUEAPPROVED 0x0D
   #define CASHLESS_POLL_RESPONSE_REVALUEDENIED 0x0E
   #define CASHLESS_POLL_RESPONSE_REVALUELIMITAMOUNT 0x0F
   #define CASHLESS_POLL_RESPONSE_USERFILEDATA 0x10
   #define CASHLESS_POLL_RESPONSE_TIMEDATEREQUEST 0x11
   #define CASHLESS_POLL_RESPONSE_DATAENTRYREQUEST 0x12
   #define CASHLESS_POLL_RESPONSE_DATAENTRYCANCEL 0x13
   #define CASHLESS_POLL_RESPONSE_ONEAH 0x14
   #define CASHLESS_POLL_RESPONSE_REQTORCV 0x1B
   #define CASHLESS_POLL_RESPONSE_RETRYDENY 0x1C
   #define CASHLESS_POLL_RESPONSE_SENDBLOCK 0x1D
   #define CASHLESS_POLL_RESPONSE_OKTOSEND 0x1E
   #define CASHLESS_POLL_RESPONSE_REQTOSEND 0x1F
   #define CASHLESS_POLL_RESPONSE_FEH 0x20
 #define CASHLESS_VEND_COMMAND 0x3
   #define CASHLESS_VEND_VENDREQUEST_COMMAND  0x00
     #define CASHLESS_VEND_VENDREQUEST_RESPONSE_VENDAPPROVED 0x05
     #define CASHLESS_VEND_VENDREQUEST_RESPONSE_VENDDENIED 0x06
   #define CASHLESS_VEND_VENDCANCEL_COMMAND 0x01
     #define CASHLESS_VEND_VENDCANCEL_RESPONSE_VENDDENIED 0x06
   #define CASHLESS_VEND_VENDSUCCESS_COMMAND 0x02
   #define CASHLESS_VEND_VENDFAILURE_COMMAND 0x03
   #define CASHLESS_VEND_SESSIONCOMPLETE_COMMAND 0x04
     #define CASHLESS_VEND_SESSIONCOMPLETE_RESPONSE_ENDSESSION 0x07
   #define CASHLESS_VEND_CASHSALE_COMMAND 0x05
   #define CASHLESS_VEND_NEGATIVEVENDREQUEST_COMMAND 0x06
     #define CASHLESS_VEND_NEGATIVEVENDREQUEST_RESPONSE_VENDAPPROVED 0x05
     #define CASHLESS_VEND_NEGATIVEVENDREQUEST_RESPONSE_VENDDENIED 0x06
 #define CASHLESS_READER_COMMAND 0x04
   #define CASHLESS_READER_READERDISABLE_COMMAND 0x00
   #define CASHLESS_READER_READERDISABLE_COMMAND 0x01
   #define CASHLESS_READER_READERCANCEL_COMMAND 0x02
     #define CASHLESS_READER_READERCANCEL_RESPONSE_CANCELLED 0x08
   #define CASHLESS_READER_DATAENTRYRESPONSE_COMMAND 0x03
 #define CASHLESS_REVALUE_COMMAND 0x05
 #define CASHLESS_REVALUE_REVALUEREQUEST_COMMAND 0x00
   #define CASHLESS_REVALUE_REVALUEREQUEST_RESPONSE_REVALUEAPPROVED 0x0D
   #define CASHLESS_REVALUE_REVALUEREQUEST_RESPONSE_REVALUEDENIED 0x0E
 #define CASHLESS_REVALUE_REVALUELIMITREQUEST_COMMAND 0x01
   #define CASHLESS_REVALUE_REVALUELIMITREQUEST_RESPONSE_REVALUELIMITAMOUNT 0x0F
   #define CASHLESS_REVALUE_REVALUELIMITREQUEST_RESPONSE_REVALUEDENIED 0x0E
 #define CASHLESS_EXPANSION_COMMAND 0x07
   #define CASHLESS_EXPANSION_REQUESTID_COMMAND 0x00
   #define CASHLESS_EXPANSION_REQUESTID_RESPONSE_PERIPHERALID 0x09
 #define CASHLESS_EXPANSION_DIAGNOSTICS_COMMAND 0xFF
   #define CASHLESS_EXPANSION_DIAGNOSTICS_RESPONSE_DIAGNOSTICRESPONSE 0xFF
 #define CASHLESS_EXPANSION_READUSERFILE_COMMAND 0x01
 #define CASHLESS_EXPANSION_READUSERFILE_RESPONSE_USERFILEDATA 0x10
 #define CASHLESS_EXPANSION_WRITEUSERFILE_COMMAND 0x02
 #define CASHLESS_EXPANSION_WRITETIMEDATE_COMMAND 0x03
 #define CASHLESS_EXPANSION_OPTIONALFEATUREENABLED_COMMAND 0x04
 #define CASHLESS_EXPANSION_FTL_REQTORCV_COMMAND 0xFA
 #define CASHLESS_EXPANSION_FTL_REQTORCV_RESPONSE_SENDBLOCK 0x1D
 #define CASHLESS_EXPANSION_FTL_REQTORCV_RESPONSE_RETRYDENY 0x1C
 #define CASHLESS_EXPANSION_FTL_RETRYDENY_COMMAND 0xFB
 #define CASHLESS_EXPANSION_FTL_SENDBLOCK_COMMAND 0xFC
 #define CASHLESS_EXPANSION_FTL_OKTOSEND_COMMAND 0xFD
 #define CASHLESS_EXPANSION_FTL_OKTOSEND_RESPONSE_SENDBLOCK 0x1D
 #define CASHLESS_EXPANSION_FTL_REQTOSEND_COMMAND 0xFE
 #define CASHLESS_EXPANSION_FTL_REQTOSEND_RESPONSE_OKTOSEND 0x1E
 #define CASHLESS_EXPANSION_FTL_REQTOSEND_RESPONSE_RETRYDENY 0x1C
 #define CASHLESS_ERROR_PAYMENTMEDIA1 0x0F
 #define CASHLESS_ERROR_INVALIDPAYMENTMEDIA1 0x1F
 #define CASHLESS_ERROR_TAMPER 0x2F
 #define CASHLESS_ERROR_MANUFACTURERDEFINED1 0x3F
 #define CASHLESS_ERROR_COMMUNICATIONS2 0x4F
 #define CASHLESS_ERROR_READERREQUIRESSERVICE2 0x5F
 #define CASHLESS_ERROR_UNASSIGNED2 0x6F
 #define CASHLESS_ERROR_MANUFACTURERDEFINED2 0x7F
 #define CASHLESS_ERROR_READERFAILURE3 0x8F
 #define CASHLESS_ERROR_COMMUNICATIONS3 0x9F
 #define CASHLESS_ERROR_PAYMENTMEDIAJAMMED3 0xAF
 #define CASHLESS_ERROR_MANUFACTURERDEFINED3 0xBF
 #define CASHLESS_ERROR_REFUNDINTERNALREADERCREDITLOST 0xCF

#endif /*PREPROCESSORS*/
